import {
  MessageCircle,
  MessageSquare,
  CreditCard,
  Bell,
  ShoppingBag,
  AlertCircle,
  Workflow,
  Star,
  Inbox,
  Brain,
  Send,
  UserPlus,
  Ticket,
  FileText,
  Plug,
  BarChart3,
  TrendingUp,
  Headphones,
  Wallet,
  Heart,
  Building2,
  GraduationCap,
  Landmark,
  Hotel,
  Plane,
  Zap,
  ShoppingCart,
  Shield,
  Bot,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  MessageCircle,
  MessageSquare,
  CreditCard,
  Bell,
  ShoppingBag,
  AlertCircle,
  Workflow,
  Star,
  Inbox,
  Brain,
  Send,
  UserPlus,
  Ticket,
  FileText,
  Plug,
  BarChart3,
  TrendingUp,
  Headphones,
  Wallet,
  Heart,
  Building2,
  GraduationCap,
  Landmark,
  Hotel,
  Plane,
  Zap,
  ShoppingCart,
  Shield,
  Bot,
};

export function getIcon(name: string, size: number = 20): React.ReactNode {
  const Icon = registry[name] ?? MessageCircle;
  return <Icon size={size} />;
}

export const colorVariants: Record<
  string,
  { bg: string; text: string; iconBg: string; hero: string; pill: string; border: string }
> = {
  blue: {
    bg: "bg-blue-50",
    text: "text-blue-600",
    iconBg: "bg-blue-100",
    hero: "from-blue-900 to-indigo-900",
    pill: "bg-blue-100 text-blue-700",
    border: "border-blue-100",
  },
  orange: {
    bg: "bg-orange-50",
    text: "text-orange-600",
    iconBg: "bg-orange-100",
    hero: "from-orange-900 to-red-900",
    pill: "bg-orange-100 text-orange-700",
    border: "border-orange-100",
  },
  green: {
    bg: "bg-emerald-50",
    text: "text-emerald-600",
    iconBg: "bg-emerald-100",
    hero: "from-emerald-900 to-teal-900",
    pill: "bg-emerald-100 text-emerald-700",
    border: "border-emerald-100",
  },
  purple: {
    bg: "bg-purple-50",
    text: "text-purple-600",
    iconBg: "bg-purple-100",
    hero: "from-purple-900 to-indigo-900",
    pill: "bg-purple-100 text-purple-700",
    border: "border-purple-100",
  },
  red: {
    bg: "bg-red-50",
    text: "text-red-600",
    iconBg: "bg-red-100",
    hero: "from-red-900 to-rose-900",
    pill: "bg-red-100 text-red-700",
    border: "border-red-100",
  },
  indigo: {
    bg: "bg-indigo-50",
    text: "text-indigo-600",
    iconBg: "bg-indigo-100",
    hero: "from-indigo-900 to-purple-900",
    pill: "bg-indigo-100 text-indigo-700",
    border: "border-indigo-100",
  },
  yellow: {
    bg: "bg-amber-50",
    text: "text-amber-600",
    iconBg: "bg-amber-100",
    hero: "from-amber-900 to-orange-900",
    pill: "bg-amber-100 text-amber-700",
    border: "border-amber-100",
  },
};
